// <auto-generated />
using JobShopAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JobShopAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("JobShopAPI.Models.Job", b =>
                {
                    b.Property<int>("IdJob")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdJob"), 1L, 1);

                    b.Property<string>("NameJob")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdJob");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("JobShopAPI.Models.JobOperation", b =>
                {
                    b.Property<int>("IdJob")
                        .HasColumnType("int");

                    b.Property<int>("IdOperation")
                        .HasColumnType("int");

                    b.HasKey("IdJob", "IdOperation");

                    b.HasIndex("IdOperation");

                    b.ToTable("JobOperation");
                });

            modelBuilder.Entity("JobShopAPI.Models.JobSimulation", b =>
                {
                    b.Property<int>("IdJob")
                        .HasColumnType("int");

                    b.Property<int>("IdSimulation")
                        .HasColumnType("int");

                    b.HasKey("IdJob", "IdSimulation");

                    b.HasIndex("IdSimulation");

                    b.ToTable("JobSimulation");
                });

            modelBuilder.Entity("JobShopAPI.Models.Machine", b =>
                {
                    b.Property<int>("IdMachine")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMachine"), 1L, 1);

                    b.Property<string>("MachineName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("time")
                        .HasColumnType("int");

                    b.HasKey("IdMachine");

                    b.ToTable("Machines");
                });

            modelBuilder.Entity("JobShopAPI.Models.MachineOperation", b =>
                {
                    b.Property<int>("IdMachine")
                        .HasColumnType("int");

                    b.Property<int>("IdOperation")
                        .HasColumnType("int");

                    b.HasKey("IdMachine", "IdOperation");

                    b.HasIndex("IdOperation");

                    b.ToTable("MachineOperation");
                });

            modelBuilder.Entity("JobShopAPI.Models.Operation", b =>
                {
                    b.Property<int>("IdOperation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdOperation"), 1L, 1);

                    b.Property<string>("OperationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdOperation");

                    b.ToTable("Operations");
                });

            modelBuilder.Entity("JobShopAPI.Models.Plan", b =>
                {
                    b.Property<int>("IdPlan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPlan"), 1L, 1);

                    b.Property<int>("IdJob")
                        .HasColumnType("int");

                    b.Property<int>("IdMachine")
                        .HasColumnType("int");

                    b.Property<int>("IdOperation")
                        .HasColumnType("int");

                    b.Property<int>("IdSimulation")
                        .HasColumnType("int");

                    b.Property<int>("finalTime")
                        .HasColumnType("int");

                    b.Property<int>("initialTime")
                        .HasColumnType("int");

                    b.HasKey("IdPlan");

                    b.HasIndex("IdJob");

                    b.HasIndex("IdMachine");

                    b.HasIndex("IdOperation");

                    b.HasIndex("IdSimulation");

                    b.ToTable("Plan");
                });

            modelBuilder.Entity("JobShopAPI.Models.Simulation", b =>
                {
                    b.Property<int>("IdSimulation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSimulation"), 1L, 1);

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("NameSimulation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdSimulation");

                    b.HasIndex("Id");

                    b.ToTable("Simulations");
                });

            modelBuilder.Entity("JobShopAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("JobShopAPI.Models.JobOperation", b =>
                {
                    b.HasOne("JobShopAPI.Models.Job", "Job")
                        .WithMany("JobOperation")
                        .HasForeignKey("IdJob")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobShopAPI.Models.Operation", "Operation")
                        .WithMany("JobOperation")
                        .HasForeignKey("IdOperation")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("Operation");
                });

            modelBuilder.Entity("JobShopAPI.Models.JobSimulation", b =>
                {
                    b.HasOne("JobShopAPI.Models.Job", "Job")
                        .WithMany("JobSimulation")
                        .HasForeignKey("IdJob")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobShopAPI.Models.Simulation", "Simulation")
                        .WithMany("JobSimulation")
                        .HasForeignKey("IdSimulation")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("Simulation");
                });

            modelBuilder.Entity("JobShopAPI.Models.MachineOperation", b =>
                {
                    b.HasOne("JobShopAPI.Models.Machine", "Machine")
                        .WithMany("MachineOperation")
                        .HasForeignKey("IdMachine")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobShopAPI.Models.Operation", "Operation")
                        .WithMany("MachineOperation")
                        .HasForeignKey("IdOperation")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Machine");

                    b.Navigation("Operation");
                });

            modelBuilder.Entity("JobShopAPI.Models.Plan", b =>
                {
                    b.HasOne("JobShopAPI.Models.Job", "Job")
                        .WithMany()
                        .HasForeignKey("IdJob")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobShopAPI.Models.Machine", "Machine")
                        .WithMany()
                        .HasForeignKey("IdMachine")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobShopAPI.Models.Operation", "Operation")
                        .WithMany()
                        .HasForeignKey("IdOperation")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobShopAPI.Models.Simulation", "Simulation")
                        .WithMany()
                        .HasForeignKey("IdSimulation")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("Machine");

                    b.Navigation("Operation");

                    b.Navigation("Simulation");
                });

            modelBuilder.Entity("JobShopAPI.Models.Simulation", b =>
                {
                    b.HasOne("JobShopAPI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("JobShopAPI.Models.Job", b =>
                {
                    b.Navigation("JobOperation");

                    b.Navigation("JobSimulation");
                });

            modelBuilder.Entity("JobShopAPI.Models.Machine", b =>
                {
                    b.Navigation("MachineOperation");
                });

            modelBuilder.Entity("JobShopAPI.Models.Operation", b =>
                {
                    b.Navigation("JobOperation");

                    b.Navigation("MachineOperation");
                });

            modelBuilder.Entity("JobShopAPI.Models.Simulation", b =>
                {
                    b.Navigation("JobSimulation");
                });
#pragma warning restore 612, 618
        }
    }
}
